USE DATABASE SNOWFLAKE_SAMPLE_DATA;
DESC TABLE TPCDS_SF100TCL.STORE_SALES;

SELECT COUNT(*) FROM TPCDS_SF100TCL.STORE_SALES;

USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS BRONZE;

USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE BRONZE.STORE_SALES_RAW AS
SELECT * 
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES
LIMIT 5000000000;

select count(*)
from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

DESC TABLE BRONZE.STORE_SALES_RAW;

select
count(*) AS total_rows,
count(ss_sales_price) as Non_null_sales_Price
from BRONZE.STORE_SALES_RAW;