USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS SILVER;

CREATE OR REPLACE TABLE SILVER.STORE_SALES_CLEAN AS
SELECT SS.SS_SOLD_DATE_SK,
    SS.SS_STORE_SK,
    SS.SS_CUSTOMER_SK,
    SS.SS_QUANTITY,
    SS.SS_SALES_PRICE
FROM BRONZE.STORE_SALES_RAW SS
JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM d
    ON ss.ss_sold_date_sk= d.d_date_sk
WHERE d.d_year BETWEEN 1998 AND 1999
AND ss.ss_sales_price IS NOT NULL
AND ss.ss_quantity > 0;

DESC TABLE SILVER.STORE_SALES_CLEAN;

SELECT MIN(SS_SALES_PRICE), MAX(SS_SALES_PRICE) FROM SILVER.STORE_SALES_CLEAN;

SELECT COUNT(*)
FROM SILVER.STORE_SALES_CLEAN
WHERE ss_sales_price IS NULL;

SELECT COUNT(*)
FROM SILVER.STORE_SALES_CLEAN
WHERE SS_QUANTITY<=0;