USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS gold;

CREATE OR REPLACE TABLE gold.sales_by_state AS
SELECT
     d.state,
     SUM(f.sales_price) AS total_sales
FROM silver.fact_sales f
JOIN silver.customer_dim d
    ON f.CUSTOMER_SK=d.CUSTOMER_SK
GROUP BY d.state;

select * from gold.sales_by_state;

CREATE OR REPLACE TABLE GOLD.SALES_BY_YEAR AS
SELECT 
     YEAR(TRANSACTION_DATE) AS SALES_YEAR,
     SUM(sales_price) as total_sales
FROM SILVER.FACT_SALES
GROUP BY sales_year;

select * from gold.sales_by_year;

CREATE OR REPLACE TABLE GOLD.MONTHLY_SALES AS 
SELECT 
DATE_TRUNC('MONTH', TRANSACTION_DATE) AS SALES_MONTH,
SUM(SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES
GROUP BY SALES_MONTH;

SELECT * FROM GOLD.MONTHLY_SALES;

CREATE OR REPLACE TABLE GOLD.TOP_STORES AS 
SELECT
STORE_ID,
SUM(SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES
GROUP BY STORE_ID
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT * FROM GOLD.TOP_STORES;

--Performance Validation

SELECT SUM(sales_price) FROM SILVER.FACT_SALES;
SELECT SUm(total_sales) FROM GOLD.SALES_BY_STATE;